# -*- coding: utf-8 -*-
import os

# Form implementation generated from reading ui file 'PyPlayerFőAblak.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot

from PlayerFunctions import PlayerFunctions


class Ui_PlayerMainWindow(object):



    def setupUi(self, PlayerMainWindow):
        PlayerMainWindow.setObjectName("PlayerMainWindow")
        PlayerMainWindow.resize(900, 400)
        PlayerMainWindow.setMinimumSize(QtCore.QSize(900, 400))
        PlayerMainWindow.setMaximumSize(QtCore.QSize(900, 400))

        self.function = PlayerFunctions()

        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(6)
        font.setItalic(False)
        PlayerMainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("B:/IntellijProjects/PyPlayer/static/music_ico.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        PlayerMainWindow.setWindowIcon(icon)

        self.centralwidget = QtWidgets.QWidget(PlayerMainWindow)
        self.centralwidget.setObjectName("centralwidget")

        song_font = QtGui.QFont()
        song_font.setFamily("Segoe UI")
        song_font.setPointSize(12)
        song_font.setBold(True)
        song_font.setItalic(True)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 130, 450, 35))
        self.label.setAutoFillBackground(False)
        self.label.setText("Zene.mp3")
        self.label.setObjectName("label")
        self.label.setFont(song_font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setStyleSheet("QLabel#label {\n"
                                 "\n"
                                 "color: rgb(253, 253, 255);""\n"
                                 "}\n"
                                 "")


        self.lblBackground = QtWidgets.QLabel(self.centralwidget)
        self.lblBackground.setGeometry(QtCore.QRect(-4, -21, 910, 540))
        self.lblBackground.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lblBackground.setAutoFillBackground(True)
        self.lblBackground.setText("")
        self.lblBackground.setTextFormat(QtCore.Qt.AutoText)
        self.lblBackground.setPixmap(QtGui.QPixmap("B:/IntellijProjects/PyPlayer/static/background.jpg"))
        self.lblBackground.setObjectName("lblBackground")

        self.btnPlay = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnPlay.setGeometry(QtCore.QRect(20, 260, 172, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnPlay.setFont(font)
        self.btnPlay.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnPlay.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btnPlay.setToolTipDuration(3)
        self.btnPlay.setAutoFillBackground(True)
        self.btnPlay.setStyleSheet("QCommandLinkButton#btnPlay {\n"
"\n"
"background: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"color: rgb(253, 253, 255);\n"
"\n"
"}\n"
"")
        self.btnPlay.setObjectName("btnPlay")
        self.btnPlay.clicked.connect(lambda: self.function.play_music(self.label))

        self.btnNext = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(270, 260, 172, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnNext.setFont(font)
        self.btnNext.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnNext.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btnNext.setToolTipDuration(3)
        self.btnNext.setAutoFillBackground(True)
        self.btnNext.setStyleSheet("QCommandLinkButton#btnNext {\n"
"\n"
"background: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"color: rgb(253, 253, 255);\n"
"\n"
"}\n"
"")
        self.btnNext.setObjectName("btnNext")
        self.btnNext.clicked.connect(lambda: self.function.next_song(self.label))

        self.btnPrevious = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnPrevious.setGeometry(QtCore.QRect(460, 260, 172, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnPrevious.setFont(font)
        self.btnPrevious.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnPrevious.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btnPrevious.setToolTipDuration(3)
        self.btnPrevious.setAutoFillBackground(True)
        self.btnPrevious.setStyleSheet("QCommandLinkButton#btnPrevious {\n"
"\n"
"background: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"color: rgb(253, 253, 255);\n"
"\n"
"}\n"
"")
        self.btnPrevious.setObjectName("btnPrevious")
        self.btnPrevious.clicked.connect(lambda: self.function.previous_song(self.label))

        self.btnPause = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnPause.setGeometry(QtCore.QRect(700, 260, 172, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnPause.setFont(font)
        self.btnPause.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnPause.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btnPause.setToolTipDuration(3)
        self.btnPause.setAutoFillBackground(True)
        self.btnPause.setStyleSheet("QCommandLinkButton#btnPause {\n"
"\n"
"background: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"color: rgb(253, 253, 255);\n"
"\n"
"}\n"
"")
        self.btnPause.setObjectName("btnPause")
        self.btnPause.clicked.connect(lambda: self.function.pause())

        self.btnMusicList = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnMusicList.setGeometry(QtCore.QRect(20, 115, 172, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnMusicList.setFont(font)
        self.btnMusicList.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnMusicList.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btnMusicList.setToolTipDuration(3)
        self.btnMusicList.setAutoFillBackground(True)
        self.btnMusicList.setStyleSheet("QCommandLinkButton#btnMusicList {\n"
"\n"
"background: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"color: rgb(253, 253, 255);\n"
"\n"
"}\n"
"")
        self.btnMusicList.setObjectName("btnMusicList")
        self.btnMusicList.clicked.connect(lambda: self.function.show_music_list())

        self.btnStop = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btnStop.setGeometry(QtCore.QRect(700, 115, 172, 55))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.btnStop.setFont(font)
        self.btnStop.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btnStop.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.btnStop.setToolTipDuration(3)
        self.btnStop.setAutoFillBackground(True)
        self.btnStop.setStyleSheet("QCommandLinkButton#btnStop {\n"
"\n"
"background: qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"color: rgb(253, 253, 255);\n"
"\n"
"}\n"
"")
        self.btnStop.setObjectName("btnStop")
        self.btnStop.clicked.connect(lambda: self.function.stop_music(self.label))

        self.lblBackground.raise_()
        self.label.raise_()
        self.btnMusicList.raise_()
        self.btnPlay.raise_()
        self.btnNext.raise_()
        self.btnPrevious.raise_()
        self.btnPause.raise_()
        self.btnStop.raise_()
        PlayerMainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(PlayerMainWindow)
        self.statusbar.setObjectName("statusbar")
        PlayerMainWindow.setStatusBar(self.statusbar)
        menu_font = QtGui.QFont()
        menu_font.setPointSize(10)
        menu_font.setBold(True)
        menu_font.setItalic(True)
        self.menubar = QtWidgets.QMenuBar(PlayerMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 14))
        self.menubar.setObjectName("menubar")
        self.menubar.setStyleSheet("QMenuBar#menubar {\n"
                                   "\n"
                                   "background: 204,229, 255;\n"
                                   "color: rgb(183, 42, 20);\n"
                                   "\n"
                                   "}\n"
                                   "")
        self.menubar.setFont(menu_font)
        self.menuF_jlok_bet_lt_se = QtWidgets.QMenu(self.menubar)
        self.menuF_jlok_bet_lt_se.setObjectName("menuF_jlok_bet_lt_se")
        self.menuS_g = QtWidgets.QMenu(self.menubar)
        self.menuS_g.setObjectName("menuS_g")
        PlayerMainWindow.setMenuBar(self.menubar)
        self.mnISelectFiles = QtWidgets.QAction(PlayerMainWindow)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.mnISelectFiles.setFont(font)
        self.mnISelectFiles.setObjectName("mnISelectFiles")
        self.mnISelectFiles.triggered.connect(lambda: self.function.open_files())

        self.mnILoadFullFOlder = QtWidgets.QAction(PlayerMainWindow)
        self.mnILoadFullFOlder.setFont(font)
        self.mnILoadFullFOlder.setObjectName("mnILoadFullFOlder")
        self.mnILoadFullFOlder.triggered.connect(lambda: self.function.open_full_folder())

        self.menuF_jlok_bet_lt_se.addAction(self.mnISelectFiles)
        self.menuF_jlok_bet_lt_se.addSeparator()
        self.menuF_jlok_bet_lt_se.addAction(self.mnILoadFullFOlder)
        self.menubar.addAction(self.menuF_jlok_bet_lt_se.menuAction())
        self.menubar.addAction(self.menuS_g.menuAction())

        self.retranslateUi(PlayerMainWindow)
        QtCore.QMetaObject.connectSlotsByName(PlayerMainWindow)

    def retranslateUi(self, PlayerMainWindow):
        _translate = QtCore.QCoreApplication.translate
        PlayerMainWindow.setWindowTitle(_translate("PlayerMainWindow", "PyPlayer - Zenelejátszó"))
        self.btnPlay.setText(_translate("PlayerMainWindow", "Lejátszás"))
        self.btnNext.setText(_translate("PlayerMainWindow", "Következő"))
        self.btnPrevious.setText(_translate("PlayerMainWindow", "Előző"))
        self.btnPause.setText(_translate("PlayerMainWindow", "Szünet"))
        self.btnMusicList.setText(_translate("PlayerMainWindow", "Zenelista"))
        self.btnStop.setText(_translate("PlayerMainWindow", "Leállítás"))
        self.menuF_jlok_bet_lt_se.setTitle(_translate("PlayerMainWindow", "Fájlok betöltése"))
        self.menuS_g.setTitle(_translate("PlayerMainWindow", "Súgó"))
        self.mnISelectFiles.setText(_translate("PlayerMainWindow", "Fájlok kiválasztása"))
        self.mnILoadFullFOlder.setText(_translate("PlayerMainWindow", "Több fájl/mappa betöltése"))
        self.label.setText(_translate("PlayerMainWindow",""))



